name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin   

    - name: Build and tag Docker image with Git commit hash
      run: |
        GIT_COMMIT_HASH=${{ github.sha }}
        docker build --build-arg GIT_COMMIT_HASH=$GIT_COMMIT_HASH -t "${{ secrets.DOCKER_USERNAME }}"/alp:$GIT_COMMIT_HASH .
        docker push "${{ secrets.DOCKER_USERNAME }}"/alp:$GIT_COMMIT_HASH

